# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddad045a565933176462d2c2ab5d340610e76971d88d744d7d1a4774804650e8040c0847a9b115b9f161899f09c0d5f31c911209542099179ac453d612fb591a

test:
  secret_key_base: dfe746c0bc89eb2fbb5a23a95af23f5d3ebf4487cc2f83ff16c75b119ad2d0de6506158bf96bb2565e226a7d3313ef4307fdbb501891f823f6c586b0cd4965ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
